name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2.0"

      - name: Install dependencies
        run: |
          brew update
          brew install curl gpg

      - name: Build PJSIP
        run: |
          curl -L -o pjproject-2.10.tar.gz https://codeload.github.com/pjsip/pjproject/tar.gz/2.10
          tar xzvf pjproject-2.10.tar.gz
          cd pjproject-2.10
          echo '#define PJSIP_DONT_SWITCH_TO_TCP 1'         >> pjlib/include/pj/config_site.h
          echo '#define PJSUA_MAX_ACC 32'                   >> pjlib/include/pj/config_site.h
          echo '#define PJMEDIA_RTP_PT_TELEPHONE_EVENTS 101' >> pjlib/include/pj/config_site.h
          echo '#define PJ_DNS_MAX_IP_IN_A_REC 32'           >> pjlib/include/pj/config_site.h
          echo '#define PJ_DNS_SRV_MAX_ADDR 32'             >> pjlib/include/pj/config_site.h
          echo '#define PJSIP_MAX_RESOLVED_ADDRESSES 32'     >> pjlib/include/pj/config_site.h
          echo '#define PJ_HAS_IPV6 1'                      >> pjlib/include/pj/config_site.h
          ./configure \
            --prefix="${{ github.workspace }}/ThirdParty/PJSIP" \
            --disable-video --disable-libyuv --disable-libwebrtc \
            --host=arm-apple-darwin \
            CFLAGS='-arch arm64 -arch x86_64 -Os -DNDEBUG -mmacosx-version-min=13.5' \
            CXXFLAGS='-arch arm64 -arch x86_64 -Os -DNDEBUG -mmacosx-version-min=13.5'
          make lib && make install
          cd ..

      - name: Build Telephone.app
        run: |
          xcodebuild \
            -project Telephone.xcodeproj \
            -scheme Telephone \
            -configuration Release \
            -arch arm64 -arch x86_64 \
            ONLY_ACTIVE_ARCH=NO \
            HEADER_SEARCH_PATHS="$(pwd)/ThirdParty/Opus/include $(pwd)/ThirdParty/LibreSSL/include $(pwd)/ThirdParty/PJSIP/include $(pwd)/ReceiptValidation/ASN1" \
            LIBRARY_SEARCH_PATHS="$(pwd)/ThirdParty/Opus/lib $(pwd)/ThirdParty/LibreSSL/lib $(pwd)/ThirdParty/PJSIP/lib" \
            OTHER_LDFLAGS="-lopus -lssl -lcrypto -lpj -lpjlib-util -lpjnath -lpjmedia -lpjmedia-codec" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SYMROOT="$(pwd)/build"

      - name: Upload built app artifact
        uses: actions/upload-artifact@v4
        with:
          name: Telephone.app
          path: build/Release/Telephone.app
