name: Build and Release1

on:
  # manual trigger if you want:
  workflow_dispatch:
  # still run on any tag push
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install curl
          brew install gpg

      - name: Build PJSIP
        run: |
          curl -o pjproject-2.10.tar.gz https://codeload.github.com/pjsip/pjproject/tar.gz/2.10
          tar xzvf pjproject-2.10.tar.gz
          cd pjproject-2.10
          cat << 'EOF' >> pjlib/include/pj/config_site.h
    #define PJSIP_DONT_SWITCH_TO_TCP 1
    #define PJSUA_MAX_ACC 32
    #define PJMEDIA_RTP_PT_TELEPHONE_EVENTS 101
    #define PJ_DNS_MAX_IP_IN_A_REC 32
    #define PJ_DNS_SRV_MAX_ADDR 32
    #define PJSIP_MAX_RESOLVED_ADDRESSES 32
    #define PJ_HAS_IPV6 1
    EOF
          ./configure --prefix="${{ github.workspace }}/ThirdParty/PJSIP" \
                      --disable-video --disable-libyuv --disable-libwebrtc \
                      --host=arm-apple-darwin \
                      CFLAGS='-arch arm64 -arch x86_64 -Os -DNDEBUG -mmacosx-version-min=10.13' \
                      CXXFLAGS='-arch arm64 -arch x86_64 -Os -DNDEBUG -mmacosx-version-min=10.13'
          make lib
          make install

      - name: Build Telephone
        run: |
          # replace this with your real Telephone build commands:
          xcodebuild \
            -project Telephone.xcodeproj \
            -scheme Telephone \
            -configuration Release \
            ONLY_ACTIVE_ARCH=NO

      # …any further steps (e.g. upload artifacts)…
