name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      - name: Install build tools
        run: |
          brew update
          brew install curl gpg autoconf automake libtool pkg-config

      - name: Build Opus
        run: |
          curl -LO https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz
          tar xzf opus-1.3.1.tar.gz
          cd opus-1.3.1
          ./configure \
            --prefix="${{ github.workspace }}/ThirdParty/Opus" \
            --disable-shared \
            CFLAGS='-arch arm64 -arch x86_64 -Os -mmacosx-version-min=13.5'
          make -j$(sysctl -n hw.ncpu)
          make install
          cd ..

      - name: Build LibreSSL
        run: |
          curl -LO https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.1.5.tar.gz
          tar xzf libressl-3.1.5.tar.gz
          cd libressl-3.1.5
          ./configure \
            --prefix="${{ github.workspace }}/ThirdParty/LibreSSL" \
            --disable-shared \
            CFLAGS='-arch arm64 -arch x86_64 -Os -mmacosx-version-min=13.5'
          make -j$(sysctl -n hw.ncpu)
          make install
          cd ..

      - name: Build PJSIP
        run: |
          curl -L -o pjproject-2.10.tar.gz https://codeload.github.com/pjsip/pjproject/tar.gz/2.10
          tar xzf pjproject-2.10.tar.gz
          cd pjproject-2.10
          # config_site.h
          for def in \
            'PJSIP_DONT_SWITCH_TO_TCP 1' \
            'PJSUA_MAX_ACC 32' \
            'PJMEDIA_RTP_PT_TELEPHONE_EVENTS 101' \
            'PJ_DNS_MAX_IP_IN_A_REC 32' \
            'PJ_DNS_SRV_MAX_ADDR 32' \
            'PJSIP_MAX_RESOLVED_ADDRESSES 32' \
            'PJ_HAS_IPV6 1'; do
            echo "#define ${def}" >> pjlib/include/pj/config_site.h
          done
          ./configure \
            --prefix="${{ github.workspace }}/ThirdParty/PJSIP" \
            --with-opus="${{ github.workspace }}/ThirdParty/Opus" \
            --with-ssl="${{ github.workspace }}/ThirdParty/LibreSSL" \
            --disable-video --disable-libyuv --disable-libwebrtc \
            --host=arm-apple-darwin \
            CFLAGS='-arch arm64 -arch x86_64 -Os -DNDEBUG -mmacosx-version-min=13.5' \
            CXXFLAGS='-arch arm64 -arch x86_64 -Os -DNDEBUG -mmacosx-version-min=13.5'
          make lib -j$(sysctl -n hw.ncpu)
          make install
          cd ..

      - name: Build Telephone.app
        run: |
          xcodebuild \
            -project Telephone.xcodeproj \
            -scheme Telephone \
            -configuration Release \
            -arch arm64 -arch x86_64 \
            ONLY_ACTIVE_ARCH=NO \
            HEADER_SEARCH_PATHS="\
$(pwd)/ThirdParty/Opus/include \
$(pwd)/ThirdParty/LibreSSL/include \
$(pwd)/ThirdParty/PJSIP/include \
$(pwd)/ReceiptValidation/ASN1" \
            LIBRARY_SEARCH_PATHS="\
$(pwd)/ThirdParty/Opus/lib \
$(pwd)/ThirdParty/LibreSSL/lib \
$(pwd)/ThirdParty/PJSIP/lib" \
            OTHER_LDFLAGS="\
-lopus \
-lssl -lcrypto \
-lpj -lpjlib-util -lpjnath -lpjmedia -lpjmedia-codec" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SYMROOT="$(pwd)/build"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Telephone.app
          path: build/Release/Telephone.app
